apiVersion: v1 
kind: Service 
metadata:
  name: hello-node-service
  labels:
    app: hello-node
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31717
  selector:
    app: hello-node
    tier: backend
---
apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: hello-node-deployment
  labels:
    app: hello-node
spec: 
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-node
        tier: backend
    spec:
      containers:
      - name: hello-node
        image: "nodehello:v1"
        ports:
        - containerPort: 8080
